export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const INIT_FAILED_PRODUCTS = 'INIT_FAILED_PRODUCTS';
export const SET_PRODUCT_PAGINATION = 'SET_PRODUCTS_PAGINATION';
export const SET_LOADING = 'SET_LOADING';